make_wave_rmd <- function(assessments, wave_num) {
  wave <- assessments[[paste0("wave", wave_num)]]
  cat("# Wave", wave_num, "\n\n")
  for (i in seq_along(wave)) {
    make_job_rmd(wave[[i]])
  }
}

make_job_rmd <- function(job_assess) {
  cat("##", job_assess$infos$job_id, "\n\n")

  cat("### Targets and Parameters", "\n\n")
  dplyr::tibble(
    target_name = job_assess$infos$targets,
    target_value = job_assess$infos$targets_val
  ) |> knitr::kable(align = "ll") |> print()

  dplyr::tibble(
    parameter = job_assess$infos$params,
    initial_range = vapply(
      job_assess$infos$params_ranges,
      \(x) paste0(x[1], " - ", x[2]),
      ""
    )
  ) |> knitr::kable(align = "ll") |> print()

  cat("\n\n")

  cat("### Parameter Space and RMSE Evolution", "\n\n")

  make_param_volume_plot(job_assess) |> print()
  make_rmse_plot(job_assess) |> print()
  cat("\n\n")

  cat("### Parameter Spreads", "\n\n")
  for (p in job_assess$infos$params) {
    make_param_spread_plot(job_assess, p) |> print()
    cat("\n\n")
  }

  cat("### Target Errors", "\n\n")
  for (t in job_assess$infos$targets) {
    make_target_err_plot(job_assess, t) |> print()
    cat("\n\n")
  }
  cat("\n\n")

}

#' Generate an html report of the auto-calibration
#'
#' The report contains descriptions of the parameters spaces and residual errors
#' over the duration of the calibration.
#'
#' @param path_to_assessments Path to an `assessments.rds` file generated by an
#'   `swfcalib` process.
#' @param output_filename Name of the html report (default = "assessment.html")
#' @param output_dir Directory where to store the report (default = current
#'   working directory)
#'
#' @export
render_assessment <- function(path_to_assessments,
                              output_filename = "assessment.html",
                              output_dir = NULL) {
  if (is.null(output_dir)) output_dir <- getwd()
  rmarkdown::render(
    system.file("rmd/assessment.Rmd", package = "swfcalib"),
    output_file = output_filename,
    output_dir = output_dir,
    knit_root_dir = getwd(),
    params = list(path_to_assessments = path_to_assessments)
  )
}
